application: afterquery
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: render.html
  upload: render.html
- url: /edit
  static_files: edit.html
  upload: edit.html
- url: /(setauth|oauth2callback)
  static_files: setauth.html
  upload: setauth.html
- url: /help
  static_files: help.html
  upload: help.html
- url: /([^/]*).js
  static_files: \1.js
  upload: .*.js
- url: /([^/]*)\.json
  static_files: \1.json
  mime_type: text/plain
  upload: .*\.json
